// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accounts": {
            "post": {
                "description": "Retrieve a paginated, filtered list of IPAccounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "List IPAccounts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAccountsResponse"
                        }
                    }
                }
            }
        },
        "/accounts/{accountId}": {
            "get": {
                "description": "Retrieve an IPAccount",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Get an IPAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAccountResponse"
                        }
                    }
                }
            }
        },
        "/disputes": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Disputes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "List Disputes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.DisputesResponse"
                        }
                    }
                }
            }
        },
        "/disputes/{disputeId}": {
            "get": {
                "description": "Retrieve a Dispute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "Get a Dispute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dispute ID",
                        "name": "disputeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.DisputeResponse"
                        }
                    }
                }
            }
        },
        "/licenseframeworks": {
            "post": {
                "description": "Retrieve a paginated, filtered list of LicenseFrameworks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "List LicenseFrameworks",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseFrameworksResponse"
                        }
                    }
                }
            }
        },
        "/licenseframeworks/{frameworkId}": {
            "get": {
                "description": "Retrieve a LicenseFramework",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "Get a LicenseFramework",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Framework ID",
                        "name": "frameworkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseFrameworkResponse"
                        }
                    }
                }
            }
        },
        "/licenses": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Licenses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "List Licenses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicensesResponse"
                        }
                    }
                }
            }
        },
        "/licenses/{licenseId}": {
            "get": {
                "description": "Retrieve a License",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "Get an License",
                "parameters": [
                    {
                        "type": "string",
                        "description": "License ID",
                        "name": "licenseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseResponse"
                        }
                    }
                }
            }
        },
        "/modules": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Modules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "List Modules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.ModulesResponse"
                        }
                    }
                }
            }
        },
        "/modules/{moduleId}": {
            "get": {
                "description": "Retrieve a Module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "Get a GetModule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Module ID",
                        "name": "moduleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.ModuleResponse"
                        }
                    }
                }
            }
        },
        "/permissions": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "List Permissions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PermissionsResponse"
                        }
                    }
                }
            }
        },
        "/permissions/{permissionId}": {
            "get": {
                "description": "Retrieve a Permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Get a Permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Permission ID",
                        "name": "permissionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PermissionResponse"
                        }
                    }
                }
            }
        },
        "/policies": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "List Policies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PoliciesResponse"
                        }
                    }
                }
            }
        },
        "/policies/{policyId}": {
            "get": {
                "description": "Retrieve a Policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Get a Policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PolicyResponse"
                        }
                    }
                }
            }
        },
        "/tags": {
            "post": {
                "description": "Retrieve a paginated, filtered list of Tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "List Tags",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.TagsResponse"
                        }
                    }
                }
            }
        },
        "/tags/{tagId}": {
            "get": {
                "description": "Retrieve a Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Get a Tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "tagId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.TagResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "beta_v0.Dispute": {
            "type": "object",
            "properties": {
                "arbitrationPolicy": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "disputeEveidenceLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "targetTag": {
                    "type": "string"
                }
            }
        },
        "beta_v0.DisputeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Dispute"
                }
            }
        },
        "beta_v0.DisputesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Dispute"
                    }
                }
            }
        },
        "beta_v0.FrameworkCreationParams": {
            "type": "object",
            "properties": {
                "activationParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "activationParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultNeedsActivation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "licenseUrl": {
                    "type": "string"
                },
                "linkParentParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "linkParentParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "beta_v0.IPAccount": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "chainId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "metadataResolverAddress": {
                    "type": "string"
                },
                "tokenContract": {
                    "type": "string"
                },
                "tokenId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.IPAccountResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.IPAccount"
                }
            }
        },
        "beta_v0.IPAccountsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.IPAccount"
                    }
                }
            }
        },
        "beta_v0.License": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licenseData": {
                    "$ref": "#/definitions/beta_v0.LicenseData"
                },
                "licenseId": {
                    "type": "string"
                },
                "receiver": {
                    "type": "string"
                }
            }
        },
        "beta_v0.LicenseData": {
            "type": "object",
            "properties": {
                "licensorIpIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "policyId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.LicenseFramework": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "frameworkCreationParams": {
                    "$ref": "#/definitions/beta_v0.FrameworkCreationParams"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "beta_v0.LicenseFrameworkResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.LicenseFramework"
                }
            }
        },
        "beta_v0.LicenseFrameworksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.LicenseFramework"
                    }
                }
            }
        },
        "beta_v0.LicenseResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.License"
                }
            }
        },
        "beta_v0.LicensesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.License"
                    }
                }
            }
        },
        "beta_v0.Module": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "beta_v0.ModuleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Module"
                }
            }
        },
        "beta_v0.ModulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Module"
                    }
                }
            }
        },
        "beta_v0.Permission": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "func": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipAccount": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "signer": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "beta_v0.PermissionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Permission"
                }
            }
        },
        "beta_v0.PermissionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Permission"
                    }
                }
            }
        },
        "beta_v0.PoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Policy"
                    }
                }
            }
        },
        "beta_v0.Policy": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "description": "PolicyData     PolicyData ` + "`" + `json:\"policyData,omitempty\"` + "`" + `",
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "frameworkId": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.PolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Policy"
                }
            }
        },
        "beta_v0.Tag": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "beta_v0.TagResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Tag"
                }
            }
        },
        "beta_v0.TagsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Tag"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
