// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/assets": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of IPAssets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAssets"
                ],
                "summary": "List IPAssets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.IpAssetRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.IPAssetsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/assets/{assetId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve an IPAsset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAssets"
                ],
                "summary": "Get an IPAsset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "assetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.IPAssetResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/collections": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Collections",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collections"
                ],
                "summary": "List Collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.CollectionsRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.CollectionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/collections/{collectionId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Collections"
                ],
                "summary": "Get an Collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Collection ID",
                        "name": "collectionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.CollectionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/disputes": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Disputes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "List Disputes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.DisputeRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.DisputesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/disputes/{disputeId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Dispute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "Get a Dispute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dispute ID",
                        "name": "disputeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.DisputeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ipapolicies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAPolicies"
                ],
                "summary": "List IPAPolicies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.IPAPolicyRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.IPAPoliciesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ipapolicies/{ipaPolicyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a IPAPolicy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAPolicies"
                ],
                "summary": "Get a IPAPolicy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IPAPolicy ID",
                        "name": "ipaPolicyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.IPAPolicyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenseframeworks": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of LicenseFrameworks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "List LicenseFrameworks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseFrameworkRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseFrameworksResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenseframeworks/{frameworkId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a LicenseFramework",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "Get a LicenseFramework",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Framework ID",
                        "name": "frameworkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseFrameworkResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licensemintingfees": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of LicenseMintingFeePaids",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseMintingFeePaids"
                ],
                "summary": "List LicenseMintingFeePays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseMintingFeePaidsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licensemintingfees/{licenseMintingFeePaidId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a LicenseMintingFeePay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseMintingFeePaids"
                ],
                "summary": "Get a LicenseMintingFeePay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "LicenseMintingFeePay ID",
                        "name": "licenseMintingFeePaidId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseMintingFeePaidResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenses": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Licenses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "List Licenses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicensesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenses/{licenseId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a License",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "Get an License",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "License ID",
                        "name": "licenseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.LicenseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/modules": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Modules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "List Modules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.ModuleRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.ModulesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/modules/{moduleId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "Get a GetModule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module ID",
                        "name": "moduleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.ModuleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/permissions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "List Permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.PermissionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PermissionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/permissions/{permissionId}": {
            "get": {
                "description": "Retrieve a Permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Get a Permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Permission ID",
                        "name": "permissionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PermissionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "List Policies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.PolicyRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PoliciesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policies/{policyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Get a Policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PolicyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policyframeworks": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of PolicyFrameworkManagers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PolicyFrameworkManagers"
                ],
                "summary": "List PolicyFrameworkManagers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.PolicyFrameworkManagerRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PolicyFrameworkManagersResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policyframeworks/{pfwmId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a PolicyFrameworkManager",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PolicyFrameworkManagers"
                ],
                "summary": "Get a PolicyFrameworkManager",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PolicyFrameworkManager ID",
                        "name": "pfwmId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.PolicyFrameworkManagerResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royalties": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Royalties",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Royalties"
                ],
                "summary": "List Royalties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltiesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royalties/{royaltyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Royalty",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Royalties"
                ],
                "summary": "Get a Royalty",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Royalty ID",
                        "name": "royaltyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypays": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of RoyaltyPays",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPays"
                ],
                "summary": "List RoyaltyPays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyPayRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyPaysResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypays/{royaltyPayId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a RoyaltyPay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPays"
                ],
                "summary": "Get a RoyaltyPay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RoyaltyPay ID",
                        "name": "royaltyPayId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyPayResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypolicies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of RoyaltyPolicies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPolicies"
                ],
                "summary": "List RoyaltyPolicies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyPoliciesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypolicies/{royaltyPolicyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a RoyaltyPolicy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPolicies"
                ],
                "summary": "Get a RoyaltyPolicy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Royalty Policy ID",
                        "name": "royaltyPolicyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.RoyaltyPolicyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "List Tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.TagRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.TagsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags/{tagId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Get a Tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "tagId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.TagResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Transactions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "List Transactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betav0.TransactionRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.TransactionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/{trxId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Transaction",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Get a Dispute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Transaction ID",
                        "name": "trxId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betav0.TransactionResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "betav0.Collection": {
            "type": "object",
            "properties": {
                "assetCount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "cancelledDisputeCount": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "judgedDisputeCount": {
                    "type": "string"
                },
                "licensesCount": {
                    "type": "string"
                },
                "raisedDisputeCount": {
                    "type": "string"
                },
                "resolvedDisputeCount": {
                    "type": "string"
                }
            }
        },
        "betav0.CollectionQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object"
                }
            }
        },
        "betav0.CollectionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Collection"
                }
            }
        },
        "betav0.CollectionsRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.CollectionQueryOptions"
                }
            }
        },
        "betav0.CollectionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Collection"
                    }
                }
            }
        },
        "betav0.Dispute": {
            "type": "object",
            "properties": {
                "arbitrationPolicy": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "currentTag": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "evidenceLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "targetIpId": {
                    "type": "string"
                },
                "targetTag": {
                    "type": "string"
                }
            }
        },
        "betav0.DisputeQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "currentTag": {
                            "type": "string"
                        },
                        "initiator": {
                            "type": "string"
                        },
                        "targetIpId": {
                            "type": "string"
                        },
                        "targetTag": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.DisputeRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.DisputeQueryOptions"
                }
            }
        },
        "betav0.DisputeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Dispute"
                }
            }
        },
        "betav0.DisputesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Dispute"
                    }
                }
            }
        },
        "betav0.FrameworkCreationParams": {
            "type": "object",
            "properties": {
                "activationParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "activationParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultNeedsActivation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "licenseUrl": {
                    "type": "string"
                },
                "linkParentParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "linkParentParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "betav0.IPAPQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "active": {
                            "type": "string"
                        },
                        "inherited": {
                            "type": "string"
                        },
                        "policyId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.IPAPoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.IPAPolicy"
                    }
                }
            }
        },
        "betav0.IPAPolicy": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "string"
                },
                "inherited": {
                    "type": "boolean"
                },
                "ipId": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                }
            }
        },
        "betav0.IPAPolicyRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.IPAPQueryOptions"
                }
            }
        },
        "betav0.IPAPolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.IPAPolicy"
                }
            }
        },
        "betav0.IPAsset": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "chainId": {
                    "type": "string"
                },
                "childIpIds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.IPAsset"
                    }
                },
                "id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/betav0.Metadata"
                },
                "metadataResolverAddress": {
                    "type": "string"
                },
                "parentIpIds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.IPAsset"
                    }
                },
                "rootIpIds": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.IPAsset"
                    }
                },
                "tokenContract": {
                    "type": "string"
                },
                "tokenId": {
                    "type": "string"
                }
            }
        },
        "betav0.IPAssetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.IPAsset"
                }
            }
        },
        "betav0.IPAssetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.IPAsset"
                    }
                }
            }
        },
        "betav0.IpAssetQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "chainId": {
                            "type": "string"
                        },
                        "metadataResolverAddress": {
                            "type": "string"
                        },
                        "tokenContract": {
                            "type": "string"
                        },
                        "tokenId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.IpAssetRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.IpAssetQueryOptions"
                }
            }
        },
        "betav0.LFWQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "creator": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.License": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licensorIpId": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                },
                "transferable": {
                    "type": "boolean"
                }
            }
        },
        "betav0.LicenseFramework": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "frameworkCreationParams": {
                    "$ref": "#/definitions/betav0.FrameworkCreationParams"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "betav0.LicenseFrameworkRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.LFWQueryOptions"
                }
            }
        },
        "betav0.LicenseFrameworkResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.LicenseFramework"
                }
            }
        },
        "betav0.LicenseFrameworksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.LicenseFramework"
                    }
                }
            }
        },
        "betav0.LicenseMintingFeePaid": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payer": {
                    "type": "string"
                },
                "receiverIpId": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "betav0.LicenseMintingFeePaidResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.LicenseMintingFeePaid"
                }
            }
        },
        "betav0.LicenseMintingFeePaidsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.LicenseMintingFeePaid"
                    }
                }
            }
        },
        "betav0.LicenseQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "licensorIpdId": {
                            "type": "string"
                        },
                        "policyId": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.LicenseRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.LicenseQueryOptions"
                }
            }
        },
        "betav0.LicenseResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.License"
                }
            }
        },
        "betav0.LicensesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.License"
                    }
                }
            }
        },
        "betav0.Metadata": {
            "type": "object",
            "properties": {
                "hash": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registrant": {
                    "type": "string"
                },
                "registrationDate": {
                    "type": "string"
                },
                "uri": {
                    "type": "string"
                }
            }
        },
        "betav0.Module": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "betav0.ModuleQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.ModuleRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.ModuleQueryOptions"
                }
            }
        },
        "betav0.ModuleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Module"
                }
            }
        },
        "betav0.ModulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Module"
                    }
                }
            }
        },
        "betav0.PFWMQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "address": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.PILPolicy": {
            "type": "object",
            "properties": {
                "attribution": {
                    "type": "boolean"
                },
                "commercialAttribution": {
                    "type": "boolean"
                },
                "commercialRevShare": {
                    "type": "string"
                },
                "commercialUse": {
                    "type": "boolean"
                },
                "commercializerChecker": {
                    "type": "string"
                },
                "commercializerCheckerData": {
                    "type": "string"
                },
                "contentRestrictions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "derivativesAllowed": {
                    "type": "boolean"
                },
                "derivativesApproval": {
                    "type": "boolean"
                },
                "derivativesAttribution": {
                    "type": "boolean"
                },
                "derivativesReciprocal": {
                    "type": "boolean"
                },
                "distributionChannels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "territories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "betav0.Permission": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "func": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "signer": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "betav0.PermissionQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "signer": {
                            "type": "string"
                        },
                        "to": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.PermissionRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.PermissionQueryOptions"
                }
            }
        },
        "betav0.PermissionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Permission"
                }
            }
        },
        "betav0.PermissionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Permission"
                    }
                }
            }
        },
        "betav0.PoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Policy"
                    }
                }
            }
        },
        "betav0.Policy": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "frameworkData": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "mintingFee": {
                    "type": "string"
                },
                "mintingFeeToken": {
                    "type": "string"
                },
                "pil": {
                    "$ref": "#/definitions/betav0.PILPolicy"
                },
                "policyFrameworkManager": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                },
                "royaltyData": {
                    "type": "string"
                },
                "royaltyPolicy": {
                    "type": "string"
                }
            }
        },
        "betav0.PolicyFrameworkManager": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licenseUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "betav0.PolicyFrameworkManagerRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.PFWMQueryOptions"
                }
            }
        },
        "betav0.PolicyFrameworkManagerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.PolicyFrameworkManager"
                }
            }
        },
        "betav0.PolicyFrameworkManagersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.PolicyFrameworkManager"
                    }
                }
            }
        },
        "betav0.PolicyQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "policyFrameworkManager": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.PolicyRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.PolicyQueryOptions"
                }
            }
        },
        "betav0.PolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Policy"
                }
            }
        },
        "betav0.RoyaltiesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Royalty"
                    }
                }
            }
        },
        "betav0.Royalty": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "royaltyPolicy": {
                    "type": "string"
                }
            }
        },
        "betav0.RoyaltyPay": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payerIpId": {
                    "type": "string"
                },
                "receiverIpId": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "betav0.RoyaltyPayQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "ipId": {
                            "type": "string"
                        },
                        "payerIpId": {
                            "type": "string"
                        },
                        "receiverIpId": {
                            "type": "string"
                        },
                        "sender": {
                            "type": "string"
                        },
                        "token": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.RoyaltyPayRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.RoyaltyPayQueryOptions"
                }
            }
        },
        "betav0.RoyaltyPayResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.RoyaltyPay"
                }
            }
        },
        "betav0.RoyaltyPaysResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.RoyaltyPay"
                    }
                }
            }
        },
        "betav0.RoyaltyPoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.RoyaltyPolicy"
                    }
                }
            }
        },
        "betav0.RoyaltyPolicy": {
            "type": "object",
            "properties": {
                "ancestorsVault": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "royaltyStack": {
                    "type": "string"
                },
                "splitClone": {
                    "type": "string"
                },
                "targetAncestors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetRoyaltyAmount": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "betav0.RoyaltyPolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.RoyaltyPolicy"
                }
            }
        },
        "betav0.RoyaltyQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "ipId": {
                            "type": "string"
                        },
                        "royaltyPolicy": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.RoyaltyRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.RoyaltyQueryOptions"
                }
            }
        },
        "betav0.RoyaltyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Royalty"
                }
            }
        },
        "betav0.Tag": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "betav0.TagQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "ipId": {
                            "type": "string"
                        },
                        "tag": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "betav0.TagRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.TagQueryOptions"
                }
            }
        },
        "betav0.TagResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Tag"
                }
            }
        },
        "betav0.TagsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Tag"
                    }
                }
            }
        },
        "betav0.Transaction": {
            "type": "object",
            "properties": {
                "actionType": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "resourceId": {
                    "type": "string"
                },
                "resourceType": {
                    "type": "string"
                }
            }
        },
        "betav0.TransactionRequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/betav0.TrxQueryOptions"
                }
            }
        },
        "betav0.TransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/betav0.Transaction"
                }
            }
        },
        "betav0.TransactionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betav0.Transaction"
                    }
                }
            }
        },
        "betav0.TrxQueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "actionType": {
                            "type": "string"
                        },
                        "ipId": {
                            "type": "string"
                        },
                        "resourceId": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
