// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/assets": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of IPAssets",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAssets"
                ],
                "summary": "List IPAssets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAssetsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/assets/{assetId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve an IPAsset",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAssets"
                ],
                "summary": "Get an IPAsset",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Asset ID",
                        "name": "assetId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAssetResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/disputes": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Disputes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "List Disputes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.DisputesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/disputes/{disputeId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Dispute",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Disputes"
                ],
                "summary": "Get a Dispute",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dispute ID",
                        "name": "disputeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.DisputeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ipapolicies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAPolicies"
                ],
                "summary": "List IPAPolicies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAPoliciesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ipapolicies/{ipaPolicyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a IPAPolicy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IPAPolicies"
                ],
                "summary": "Get a IPAPolicy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IPAPolicy ID",
                        "name": "ipaPolicyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.IPAPolicyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenseframeworks": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of LicenseFrameworks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "List LicenseFrameworks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseFrameworksResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenseframeworks/{frameworkId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a LicenseFramework",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "LicenseFrameworks"
                ],
                "summary": "Get a LicenseFramework",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Framework ID",
                        "name": "frameworkId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseFrameworkResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenses": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Licenses",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "List Licenses",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicensesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/licenses/{licenseId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a License",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Licenses"
                ],
                "summary": "Get an License",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "License ID",
                        "name": "licenseId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.LicenseResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/modules": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Modules",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "List Modules",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.ModulesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/modules/{moduleId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Module",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Modules"
                ],
                "summary": "Get a GetModule",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Module ID",
                        "name": "moduleId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.ModuleResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/permissions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Permissions",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "List Permissions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PermissionsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/permissions/{permissionId}": {
            "get": {
                "description": "Retrieve a Permission",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Permissions"
                ],
                "summary": "Get a Permission",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Permission ID",
                        "name": "permissionId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PermissionResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policies": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Policies",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "List Policies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PoliciesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policies/{policyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Policy",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Policies"
                ],
                "summary": "Get a Policy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Policy ID",
                        "name": "policyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PolicyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policyframeworks/{pfwmId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a PolicyFrameworkManager",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PolicyFrameworkManagers"
                ],
                "summary": "Get a PolicyFrameworkManager",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PolicyFrameworkManager ID",
                        "name": "pfwmId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PolicyFrameworkManagerResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/policymanagers": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of PolicyFrameworkManagers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PolicyFrameworkManagers"
                ],
                "summary": "List PolicyFrameworkManagers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.PolicyFrameworkManagersResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royalties": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Royalties",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Royalties"
                ],
                "summary": "List Royalties",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.RoyaltiesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royalties/{royaltyId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Royalty",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Royalties"
                ],
                "summary": "Get a Royalty",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Royalty ID",
                        "name": "royaltyId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.RoyaltyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypays": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of RoyaltyPays",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPays"
                ],
                "summary": "List RoyaltyPays",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.RoyaltyPaysResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/royaltypays/{royaltyPayId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a RoyaltyPay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "RoyaltyPays"
                ],
                "summary": "Get a RoyaltyPay",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RoyaltyPay ID",
                        "name": "royaltyPayId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.RoyaltyPayResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a paginated, filtered list of Tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "List Tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Query Parameters (",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/options.RequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.TagsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tags/{tagId}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve a Tag",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tags"
                ],
                "summary": "Get a Tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API Key",
                        "name": "X-API-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "tagId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/beta_v0.TagResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "beta_v0.Dispute": {
            "type": "object",
            "properties": {
                "arbitrationPolicy": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "currentTag": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "evidenceLink": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "initiator": {
                    "type": "string"
                },
                "targetIpId": {
                    "type": "string"
                },
                "targetTag": {
                    "type": "string"
                }
            }
        },
        "beta_v0.DisputeResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Dispute"
                }
            }
        },
        "beta_v0.DisputesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Dispute"
                    }
                }
            }
        },
        "beta_v0.FrameworkCreationParams": {
            "type": "object",
            "properties": {
                "activationParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "activationParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "defaultNeedsActivation": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "licenseUrl": {
                    "type": "string"
                },
                "linkParentParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "linkParentParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamDefaultValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mintingParamVerifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "beta_v0.IPAPoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.IPAPolicy"
                    }
                }
            }
        },
        "beta_v0.IPAPolicy": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "string"
                },
                "inherited": {
                    "type": "boolean"
                },
                "ipId": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.IPAPolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.IPAPolicy"
                }
            }
        },
        "beta_v0.IPAsset": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "chainId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "metadata": {
                    "type": "string"
                },
                "metadataResolverAddress": {
                    "type": "string"
                },
                "tokenContract": {
                    "type": "string"
                },
                "tokenId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.IPAssetResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.IPAsset"
                }
            }
        },
        "beta_v0.IPAssetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.IPAsset"
                    }
                }
            }
        },
        "beta_v0.License": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licensorIpId": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                },
                "transferable": {
                    "type": "boolean"
                }
            }
        },
        "beta_v0.LicenseFramework": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "frameworkCreationParams": {
                    "$ref": "#/definitions/beta_v0.FrameworkCreationParams"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "beta_v0.LicenseFrameworkResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.LicenseFramework"
                }
            }
        },
        "beta_v0.LicenseFrameworksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.LicenseFramework"
                    }
                }
            }
        },
        "beta_v0.LicenseResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.License"
                }
            }
        },
        "beta_v0.LicensesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.License"
                    }
                }
            }
        },
        "beta_v0.Module": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "module": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "beta_v0.ModuleResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Module"
                }
            }
        },
        "beta_v0.ModulesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Module"
                    }
                }
            }
        },
        "beta_v0.Permission": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "func": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "signer": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "beta_v0.PermissionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Permission"
                }
            }
        },
        "beta_v0.PermissionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Permission"
                    }
                }
            }
        },
        "beta_v0.PoliciesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Policy"
                    }
                }
            }
        },
        "beta_v0.Policy": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "policy": {
                    "type": "string"
                },
                "policyFrameworkManager": {
                    "type": "string"
                },
                "policyId": {
                    "type": "string"
                }
            }
        },
        "beta_v0.PolicyFrameworkManager": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "licenseUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "beta_v0.PolicyFrameworkManagerResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.PolicyFrameworkManager"
                }
            }
        },
        "beta_v0.PolicyFrameworkManagersResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.PolicyFrameworkManager"
                    }
                }
            }
        },
        "beta_v0.PolicyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Policy"
                }
            }
        },
        "beta_v0.RoyaltiesResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Royalty"
                    }
                }
            }
        },
        "beta_v0.Royalty": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "royaltyPolicy": {
                    "type": "string"
                }
            }
        },
        "beta_v0.RoyaltyPay": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "payerIpId": {
                    "type": "string"
                },
                "receiverIpId": {
                    "type": "string"
                },
                "sender": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "beta_v0.RoyaltyPayResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.RoyaltyPay"
                }
            }
        },
        "beta_v0.RoyaltyPaysResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.RoyaltyPay"
                    }
                }
            }
        },
        "beta_v0.RoyaltyResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Royalty"
                }
            }
        },
        "beta_v0.Tag": {
            "type": "object",
            "properties": {
                "blockNumber": {
                    "type": "string"
                },
                "blockTimestamp": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipId": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        },
        "beta_v0.TagResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/beta_v0.Tag"
                }
            }
        },
        "beta_v0.TagsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/beta_v0.Tag"
                    }
                }
            }
        },
        "options.QueryOptions": {
            "type": "object",
            "properties": {
                "orderBy": {
                    "type": "string"
                },
                "orderDirection": {
                    "type": "string"
                },
                "pagination": {
                    "type": "object",
                    "properties": {
                        "limit": {
                            "type": "integer"
                        },
                        "offset": {
                            "type": "integer"
                        }
                    }
                },
                "where": {
                    "type": "object",
                    "properties": {
                        "creator": {
                            "type": "string"
                        },
                        "frameworkId": {
                            "type": "string"
                        },
                        "ipAsset": {
                            "type": "string"
                        },
                        "ipId": {
                            "type": "string"
                        },
                        "receiver": {
                            "type": "string"
                        },
                        "tokenContract": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "options.RequestBody": {
            "type": "object",
            "properties": {
                "options": {
                    "$ref": "#/definitions/options.QueryOptions"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
